// Builds the journal from content/journal/*.md into static, crawlable HTML.
//
//   content/journal/<slug>.md  ->  journal/<slug>/index.html   (full article in the HTML)
//                              ->  journal/index.html          (list between the journal markers)
//                              ->  sitemap.xml, feed.xml, llms.txt
//
// Run from the repo root or tools/:  node tools/build.mjs
// Posts are edited at /admin (Sveltia CMS); GitHub Actions runs this on every push.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import matter from 'gray-matter';
import { marked } from 'marked';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SITE = 'https://aderemisalako.me';
const AUTHOR = 'Aderemi A. Salako';
const DEFAULT_IMAGE = `${SITE}/assets/og-share-v6.jpg`;
const GENERATED = 'Generated by tools/build.mjs';
const CONTENT = path.join(ROOT, 'content/journal');
const JOURNAL = path.join(ROOT, 'journal');


const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

const esc = (s) => String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const abs = (u) => (!u ? '' : /^https?:/.test(u) ? u : SITE + (u.startsWith('/') ? u : '/' + u));
const toIso = (d) => (d instanceof Date ? d : new Date(d)).toISOString().slice(0, 10);
const display = (iso) => { const [y, m, d] = iso.split('-'); return `${d} ${MONTHS[+m - 1]} ${y}`; };
const plain = (md) => md.replace(/!\[[^\]]*\]\([^)]*\)/g, '').replace(/\[([^\]]*)\]\([^)]*\)/g, '$1').replace(/[#>*_`~-]/g, ' ').replace(/\s+/g, ' ').trim();

export function slugify(title) {
  return String(title).toLowerCase()
    .replace(/['‘’"“”]/g, '')
    .replace(/[^a-z0-9]+/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '');
}

// images get lazy loading; links off-site open in a new tab
const renderer = new marked.Renderer();
renderer.image = ({ href, title, text }) =>
  `<img src="${esc(href)}" alt="${esc(text)}"${title ? ` title="${esc(title)}"` : ''} loading="lazy" />`;
renderer.link = function ({ href, title, tokens }) {
  const inner = this.parser.parseInline(tokens);
  const ext = /^https?:/.test(href) && !href.startsWith(SITE);
  return `<a href="${esc(href)}"${title ? ` title="${esc(title)}"` : ''}${ext ? ' target="_blank" rel="noopener"' : ''}>${inner}</a>`;
};
marked.use({ renderer, gfm: true });

function loadPosts() {
  if (!fs.existsSync(CONTENT)) return [];
  const seen = new Set();
  return fs.readdirSync(CONTENT).filter((f) => f.endsWith('.md')).map((file) => {
    const { data, content } = matter(fs.readFileSync(path.join(CONTENT, file), 'utf8'));
    if (!data.title || !data.date) throw new Error(`${file}: title and date are required`);
    let slug = slugify(data.slug || file.replace(/\.md$/, ''));
    if (seen.has(slug)) throw new Error(`${file}: slug "${slug}" is used twice`);
    seen.add(slug);
    const isoDate = toIso(data.date);
    const text = plain(content);
    const words = text ? text.split(' ').length : 0;
    const firstPara = (content.split(/\n\s*\n/).map((p) => p.trim()).find((p) => p && !/^[#>!]/.test(p)) || '');
    const excerpt = data.excerpt || data.description || plain(firstPara).slice(0, 180);
    return {
      ...data, slug, isoDate, content,
      status: data.status || 'published',
      displayDate: display(isoDate),
      readTime: data.readTime || `${Math.max(1, Math.ceil(words / 200))} min read`,
      description: data.description || excerpt,
      excerpt,
      // folder pages use trailing slashes: GitHub Pages 301s the slashless form
      url: `${SITE}/journal/${slug}/`,
      path: `/journal/${slug}/`,
      seoTitle: data.seoTitle || (`${data.title} | Aderemi Salako`.length <= 60 ? `${data.title} | Aderemi Salako` : data.title),
      image: abs(data.cover) || DEFAULT_IMAGE,
    };
  }).sort((a, b) => b.isoDate.localeCompare(a.isoDate));
}

function fill(tpl, vars) {
  return tpl.replace(/\{\{(\w+)\}\}/g, (_, k) => (k in vars ? vars[k] : ''));
}

const SUBSCRIBE_URL = 'https://salakoaderemi.substack.com/?r=7bt26&utm_campaign=subscribe-page-share-screen&utm_medium=web'.replace(/&/g, '&amp;');

function writePost(post, tpl) {
  // marked escapes apostrophes as &#39;; plain ones are valid HTML and easier to read
  let body = marked.parse(post.content).replace(/&#39;/g, "'");
  // closing line: related links (footnote, Markdown) and/or the Substack source
  const source = post.sourceUrl ? `Originally published on <a href="${esc(post.sourceUrl)}" target="_blank" rel="noopener">Substack</a>.` : '';
  const note = post.footnote ? marked.parseInline(String(post.footnote)) : '';
  // every journal post ends with a link to subscribe to the Substack
  const subscribe = `<a href="${SUBSCRIBE_URL}" target="_blank" rel="noopener">Subscribe to my Substack</a> to get new posts as I write them.`;
  const closing = [note, source].filter(Boolean).join(' ');
  body += `\n<p class="article-source">${subscribe}${closing ? `<br />${closing}` : ''}</p>`;
  const person = { '@type': 'Person', '@id': `${SITE}/#person`, name: AUTHOR };
  const jsonLd = JSON.stringify({
    '@context': 'https://schema.org',
    '@type': 'BlogPosting',
    headline: post.title,
    description: post.description,
    datePublished: post.isoDate,
    dateModified: post.updated ? toIso(post.updated) : post.isoDate,
    image: post.image,
    url: post.url,
    mainEntityOfPage: post.url,
    articleSection: post.section || post.tag,
    inLanguage: 'en',
    author: { ...person, url: `${SITE}/about` },
    publisher: person,
  }, null, 2).replace(/</g, '\\u003c');
  const html = fill(tpl, {
    slug: post.slug,
    title: esc(post.title),
    seoTitle: esc(post.seoTitle),
    description: esc(post.description),
    url: post.url,
    image: esc(post.image),
    isoDate: post.isoDate,
    displayDate: post.displayDate,
    readTime: esc(post.readTime),
    tag: esc(post.tag || 'Journal'),
    dekHtml: post.dek ? `<p class="article-dek">${esc(post.dek)}</p>` : '',
    bodyHtml: body.trim().split('\n').map((l) => '            ' + l).join('\n'),
    jsonLd,
  });
  const dir = path.join(JOURNAL, post.slug);
  fs.mkdirSync(dir, { recursive: true });
  // drop lines left blank by empty fields (e.g. no subtitle)
  fs.writeFileSync(path.join(dir, 'index.html'), html.replace(/\n[ \t]+(?=\n)/g, ''));
}

// remove generated post folders whose markdown was deleted or unpublished
function pruneStale(live) {
  for (const name of fs.readdirSync(JOURNAL)) {
    const file = path.join(JOURNAL, name, 'index.html');
    if (live.has(name) || !fs.existsSync(file)) continue;
    if (fs.readFileSync(file, 'utf8').includes(GENERATED)) fs.rmSync(path.join(JOURNAL, name), { recursive: true });
  }
}

function journalRow(p) {
  const thumb = p.cover
    ? `<span class="journal-thumb">\n                  <img src="${esc(p.cover)}" alt="Cover image for ${esc(p.title)}" loading="lazy" width="72" height="72"${p.coverPosition ? ` style="object-position:${esc(p.coverPosition)}"` : ''} />\n                </span>`
    : '<span class="journal-thumb is-placeholder" aria-hidden="true"></span>';
  const live = p.status === 'published';
  const open = live ? `<a class="journal-row is-link" href="${p.path}">` : '<div class="journal-row">';
  const foot = live ? `<span class="journal-tag">${esc(p.tag || 'Journal')}</span>` : '<span class="journal-soon">Full write-up coming soon</span>';
  return `            ${open}
              <div class="journal-media">
                ${thumb}
                <time class="journal-date" datetime="${p.isoDate}">${p.displayDate}</time>
              </div>
              <div>
                <h2>${esc(p.title)}</h2>
                <p class="journal-excerpt">${esc(p.excerpt)}</p>
                ${foot}
              </div>
            ${live ? '</a>' : '</div>'}`;
}

function writeIndex(listed) {
  const file = path.join(JOURNAL, 'index.html');
  const html = fs.readFileSync(file, 'utf8');
  const re = /(<!-- journal:start[^>]*-->)[\s\S]*?(\s*<!-- journal:end -->)/;
  if (!re.test(html)) throw new Error('journal/index.html is missing the <!-- journal:start --> / <!-- journal:end --> markers');
  fs.writeFileSync(file, html.replace(re, (_, a, b) => `${a}\n${listed.map(journalRow).join('\n')}${b}`));
}

function writeSitemap(published) {
  const file = path.join(ROOT, 'sitemap.xml');
  const old = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : '';
  // keep every hand-listed page that is not a journal post
  const keep = [...old.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => m[1]).filter((u) => !/\/journal\/[^/]+\/?$/.test(u));
  if (!keep.length) keep.push(`${SITE}/`, `${SITE}/journal/`);
  const lastmods = Object.fromEntries([...old.matchAll(/<loc>([^<]+)<\/loc>(?:<lastmod>([^<]+)<\/lastmod>)?/g)].map((m) => [m[1], m[2]]));
  const latest = published.map((p) => (p.updated ? toIso(p.updated) : p.isoDate)).sort().pop();
  const rows = keep.map((u) => {
    const isJournal = /\/journal\/?$/.test(u);
    const mod = isJournal && latest && (!lastmods[u] || latest > lastmods[u]) ? latest : lastmods[u];
    return `  <url><loc>${u}</loc>${mod ? `<lastmod>${mod}</lastmod>` : ''}</url>`;
  });
  const journalAt = rows.findIndex((r) => /\/journal\/?<\/loc>/.test(r));
  const postRows = published.map((p) => `  <url><loc>${p.url}</loc><lastmod>${lastmods[p.url] && lastmods[p.url] > p.isoDate && !p.updated ? lastmods[p.url] : (p.updated ? toIso(p.updated) : p.isoDate)}</lastmod></url>`);
  rows.splice(journalAt >= 0 ? journalAt + 1 : rows.length, 0, ...postRows);
  fs.writeFileSync(file, `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${rows.join('\n')}\n</urlset>\n`);
}

// the human-readable /sitemap page lists posts between journal markers
function writeHtmlSitemap(published) {
  const file = path.join(ROOT, 'sitemap.html');
  if (!fs.existsSync(file)) return;
  const html = fs.readFileSync(file, 'utf8');
  const re = /(<!-- journal:start[^>]*-->)[\s\S]*?(\s*<!-- journal:end -->)/;
  if (!re.test(html)) return;
  const items = published.map((p) => `            <li><a href="${p.path}">${esc(p.title)}</a><span>Journal &middot; ${p.displayDate}</span></li>`);
  fs.writeFileSync(file, html.replace(re, (_, a, b) => `${a}\n${items.join('\n')}${b}`));
}

function writeFeed(published) {
  const items = published.slice(0, 30).map((p) => `    <item>
      <title>${esc(p.title)}</title>
      <link>${p.url}</link>
      <guid isPermaLink="true">${p.url}</guid>
      <pubDate>${new Date(p.isoDate + 'T09:00:00Z').toUTCString()}</pubDate>
      <category>${esc(p.tag || 'Journal')}</category>
      <description>${esc(p.description)}</description>
    </item>`).join('\n');
  fs.writeFileSync(path.join(ROOT, 'feed.xml'), `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>Remi Visuals Journal</title>
    <link>${SITE}/journal/</link>
    <atom:link href="${SITE}/feed.xml" rel="self" type="application/rss+xml" />
    <description>Notes on craft — colour, pacing, and process — from ${AUTHOR}.</description>
    <language>en</language>
${items}
  </channel>
</rss>
`);
}

// llms.txt: a plain map of the site for AI assistants (https://llmstxt.org)
function writeLlms(published) {
  const posts = published.map((p) => `- [${p.title}](${p.url}): ${p.description}`).join('\n');
  fs.writeFileSync(path.join(ROOT, 'llms.txt'), `# Remi Visuals — ${AUTHOR}

> Portfolio and journal of ${AUTHOR} (Remi Visuals), a video editor and colourist working in DaVinci Resolve. Cinematic video editing, colour grading, motion design, creative direction and social content. Based in Nigeria, working worldwide.

## Pages

- [Home](${SITE}/): Who I am, selected work and how to hire me
- [Portfolio](${SITE}/portfolio): Selected editing, colour and photography work
- [Red Eye Effect](${SITE}/work/red-eye-effect/): Case study — a cinematic colour study graded in DaVinci Resolve
- [Services](${SITE}/services): YouTube editing, short-form video, DaVinci Resolve colour grading and content strategy
- [About](${SITE}/about): Background and approach
- [Contact](${SITE}/contact): Hire me for editing or colour work — hello@aderemisalako.me

## Journal

${posts}

## Optional

- [RSS feed](${SITE}/feed.xml)
- [Substack](https://salakoaderemi.substack.com): Personal essays, mirrored to the journal
`);
}

export function build() {
  const tpl = fs.readFileSync(path.join(ROOT, 'tools/templates/post.html'), 'utf8');
  const all = loadPosts();
  const published = all.filter((p) => p.status === 'published');
  const listed = all.filter((p) => p.status === 'published' || p.status === 'coming-soon');
  published.forEach((p) => writePost(p, tpl));
  pruneStale(new Set(published.map((p) => p.slug)));
  writeIndex(listed);
  writeSitemap(published);
  writeHtmlSitemap(published);
  writeFeed(published);
  writeLlms(published);
  console.log(`Built ${published.length} published post(s), ${listed.length - published.length} coming soon, ${all.length - listed.length} draft(s).`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) build();
